# Generated by Django 4.1.1 on 2022-09-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                (
                    "introduction",
                    models.TextField(max_length=500, verbose_name="Introduction"),
                ),
                (
                    "recent_events",
                    models.TextField(max_length=20, verbose_name="Recent_events"),
                ),
                ("event_date", models.DateTimeField(verbose_name="Event_date")),
                (
                    "autobiography",
                    models.TextField(max_length=500, verbose_name="Autobiography"),
                ),
            ],
        ),
        migrations.DeleteModel(name="Event",),
    ]
