# Generated by Django 4.1.1 on 2022-09-19 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_information_delete_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.interest",
            ),
        ),
    ]
