# Generated by Django 4.1.1 on 2022-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_information_introduction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
