# Generated by Django 4.1.1 on 2022-09-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_information_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papername",
                    models.CharField(max_length=1000, verbose_name="Papername"),
                ),
                (
                    "papercontent",
                    models.TextField(max_length=1000, verbose_name="Papercontent"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
