# Generated by Django 4.1.1 on 2022-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_paper"),
    ]

    operations = [
        migrations.CreateModel(
            name="all_abouts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience",
                    models.CharField(max_length=100, verbose_name="Experience"),
                ),
                (
                    "content",
                    models.TextField(max_length=1000, verbose_name="Experience"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="paper",
            name="papername",
            field=models.CharField(max_length=100, verbose_name="Papername"),
        ),
    ]
