# Generated by Django 4.1.2 on 2022-10-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_all_aboutus_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(max_length=10000, verbose_name="content")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="all_aboutus",
            name="content",
            field=models.TextField(max_length=10000, verbose_name="content"),
        ),
    ]
