# Generated by Django 4.1.2 on 2022-10-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_homepost_website_homepost_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepost",
            name="writer",
            field=models.CharField(max_length=20, null=True, verbose_name="writer"),
        ),
    ]
